{% set data = load_setup_py_data() %}

package:
  name: convert_and_download
  version: {{ data['version'] }}

source:
  path: ..

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  noarch: python

requirements:
  build:
    - python
    - setuptools
    - pip

  run:
    - python >=3.6,<4.0
    - thermohw >=0.2,<1.0

test:
  imports:
    - convert_and_download

  # requires:
  #   - pytest >=3.2.0
  #   - pytest-cov >=2.3.1

  # commands:
  #   - pytest -vv --pyargs convert_and_download

about:
  home: {{ data['url'] }}
  license: BSD 3-Clause
  license_file: LICENSE
  license_family: BSD

  summary: {{ data['description'] }}
  description: Convert one or more ipynb files to PDF, merge them, and download the resulting file.
  doc_url: https://bryanwweber.github.io/convert_and_download
  dev_url: {{ data['url'] }}
